name       : gdbm
version    : 1.18.1
release    : 7
source     :
    - ftp://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz : 86e613527e5dba544e73208f42b78b7c022d4fa5a6d5498bf18c8d6f745b91dc
homepage   : https://www.gnu.org.ua/software/gdbm/
license    : GPL-3.0-or-later
summary    : Standard GNU database libraries
component  : programming.library
description: |
    GNU dbm is a set of database routines that use extensible hashing. It works similar to the standard UNIX dbm routines.
patterns   :
    - /usr/lib64/*.so
emul32     : yes
setup      : |
    %configure --disable-static --enable-libgdbm-compat
build      : |
    %make
install    : |
    %make_install
    install -D AUTHORS %installroot%/usr/share/doc/gdbm/AUTHORS
    install -D COPYING %installroot%/usr/share/doc/gdbm/COPYING
    install -D ChangeLog %installroot%/usr/share/doc/gdbm/ChangeLog
check      : |
    %make check
