name       : gdbm
version    : 1.13
release    : 4
source     :
    - http://gnu.mirror.iweb.com/gdbm/gdbm-1.13.tar.gz : 9d252cbd7d793f7b12bcceaddda98d257c14f4d1890d851c386c37207000a253
homepage   : http://www.gnu.org/software/gdbm/gdbm.html
license    : GPL-3.0
summary    : Standard GNU database libraries
component  : system.base
description: |
    GNU dbm is a set of database routines that use extensible hashing. It works similar to the standard UNIX dbm routines.
patterns   :
    - /usr/lib64/*.so
emul32     : yes
setup      : |
    %configure --disable-static \
               --enable-libgdbm-compat \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D AUTHORS %installroot%/usr/share/doc/gdbm/AUTHORS
    install -D COPYING %installroot%/usr/share/doc/gdbm/COPYING
    install -D ChangeLog %installroot%/usr/share/doc/gdbm/ChangeLog
