name        : gdbm
version     : 1.10
release     : 3
source      :
    - http://gnu.mirror.iweb.com/gdbm/gdbm-1.10.tar.gz : 23f8134c5b94bbfb06d756a6b78f074fba6e6028cf2fe01341d40b26db773441
homepage    : http://www.gnu.org/software/gdbm/gdbm.html
license     : GPL-2.0+
summary     : Standard GNU database libraries
component   : system.base
description : |
    GNU dbm is a set of database routines that use extensible hashing. It works similar to the standard UNIX dbm routines.
patterns    :
    - /usr/lib64/*.so
setup      : |
    %configure --disable-static \
               --enable-libgdbm-compat
build      : |
    %make
install    : |
    %make_install
    install -D AUTHORS %installroot%/usr/share/doc/gdbm/AUTHORS
    install -D COPYING %installroot%/usr/share/doc/gdbm/COPYING
    install -D ChangeLog %installroot%/usr/share/doc/gdbm/ChangeLog
