name       : gdbm
version    : 1.14.1
release    : 6
source     :
    - ftp://ftp.gnu.org/gnu/gdbm/gdbm-1.14.1.tar.gz : cdceff00ffe014495bed3aed71c7910aa88bf29379f795abc0f46d4ee5f8bc5f
homepage   : http://www.gnu.org.ua/software/gdbm/
license    : GPL-3.0
summary    : Standard GNU database libraries
component  : programming.library
description: |
    GNU dbm is a set of database routines that use extensible hashing. It works similar to the standard UNIX dbm routines.
patterns   :
    - /usr/lib64/*.so
emul32     : yes
setup      : |
    %configure --disable-static \
               --enable-libgdbm-compat
build      : |
    %make
install    : |
    %make_install
    install -D AUTHORS %installroot%/usr/share/doc/gdbm/AUTHORS
    install -D COPYING %installroot%/usr/share/doc/gdbm/COPYING
    install -D ChangeLog %installroot%/usr/share/doc/gdbm/ChangeLog
check      : |
    %make check
