name       : gdbm
version    : '1.19'
release    : 9
source     :
    - https://ftp.gnu.org/gnu/gdbm/gdbm-1.19.tar.gz : 37ed12214122b972e18a0d94995039e57748191939ef74115b1d41d8811364bc
homepage   : https://www.gnu.org.ua/software/gdbm/
license    : GPL-3.0-or-later
summary    : Standard GNU database libraries
component  : programming.library
description: |
    GNU dbm is a set of database routines that use extensible hashing. It works similar to the standard UNIX dbm routines.
patterns   :
    - /usr/lib64/*.so
emul32     : yes
builddeps  :
    - pkgconfig32(ncursesw)
setup      : |
    %configure --disable-static --enable-libgdbm-compat
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
check      : |
    %make check
